[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_add = '''
    let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = ['deoplete.nvim']
on_i = 1
on_ft = ['python']
hook_add = '''
    let g:deoplete#sources#jdei#python_path = '/home/chasen/.pyenv/versions/anaconda3-5.0.1/bin//python'
'''

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['html']

[[plugins]]
repo = 'cohama/lexima.vim'
